apiVersion: v1
kind: Service
metadata:
  name: drupal-service
  namespace: ns-portalxmdrupal
spec:
  selector:
    app: drupal        # ðŸ‘ˆ matches pod label
  ports:
  - port: 80           # Service port
    targetPort: 80     # Container port (change if your Drupal listens on another port)
    protocol: TCP
  type: ClusterIP
