apiVersion: v1
kind: Service
metadata:
  name: front-app-service
  namespace: ns-portalfront-app
spec:
  selector:
    app: front-app        # ðŸ‘ˆ matches pod label
  ports:
  - port: 80           # Service port
    targetPort: 80     # Container port (change if your front-app listens on another port)
    protocol: TCP
  type: ClusterIP
