apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-drupal
  namespace: ns-portalxmdrupal
  annotations:
    azure.workload.identity/client-id: "$IDENTITY_CLIENT_ID"
  labels:
    app: drupal
    environment: "qa"
