apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-drupal
  namespace: ns-portalxmdrupal
  annotations:
    azure.workload.identity/client-id: "123-0cc4-4539-843a-123"
  labels:
    app: drupal
    environment: "prb"
